import Head from 'next/head';

// Components
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <div className=" grid min-h-screen  grid-rows-main bg-primary">
      <Head>
        <title>CoffeeScript | Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="">
        <span>body</span>
      </main>

      <Footer />
    </div>
  );
}
